"""Created Topic model

Revision ID: d0ce2938efc7
Revises: 3b25c7ff29f2
Create Date: 2024-09-17 13:24:02.167783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ce2938efc7'
down_revision: Union[str, None] = '3b25c7ff29f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('job_field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_field_id'], ['job_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    # ### end Alembic commands ###
